steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/bootcampproject-5-465900/bootcampproject-5-service-main'
      - './App'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'bootcampproject-5-service-main'
      - '--image=gcr.io/bootcampproject-5-465900/bootcampproject-5-service-main'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'

images:
  - 'gcr.io/bootcampproject-5-465900/bootcampproject-5-service-main'
