steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/bootcampproject-5-465900/bootcampproject-5-repo/app-image:$SHORT_SHA',
      '-f',
      'Scripts/dockerfile',
      'Scripts'
    ]

- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'us-central1-docker.pkg.dev/bootcampproject-5-465900/bootcampproject-5-repo/app-image:$SHORT_SHA'
    ]

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    [
      'run',
      'deploy',
      'bootcampproject-5-service-main',
      '--image',
      'us-central1-docker.pkg.dev/bootcampproject-5-465900/bootcampproject-5-repo/app-image:$SHORT_SHA',
      '--region',
      'us-central1',
      '--platform',
      'managed',
      '--allow-unauthenticated',
      '--port',
      '8080'
    ]

images:
- 'us-central1-docker.pkg.dev/bootcampproject-5-465900/bootcampproject-5-repo/app-image:$SHORT_SHA'
